version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: |
            pip install --upgrade pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            python -m unittest discover
            
workflows:
  main:
    jobs:
      - build
