version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            python --version
            
workflows:
  main:
    jobs:
      - build
      - python/test:
          pkg-manager: pip
